@url = http://localhost:3000

### Get all Acara
GET {{url}}/acara
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw

### Get Acara By ID
GET {{url}}/acara/692eaaa3cda530d43888c77c
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw

### Search Acara
GET {{url}}/acara?search=Kanak
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw
