@url = http://localhost:3000

GET {{url}}/siaran
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw

### Get Siaran By ID
GET {{url}}/siaran/692ea5f9dd234d3211c80753
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw