@url = http://localhost:3000

GET {{url}}/siaran
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw

### Get Siaran By ID
GET {{url}}/siaran/{{siaranId}}
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw

### Get Siaran Categories
GET http://localhost:3000/siaran/categories
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw