# @url = http://localhost:3000
@url = https://sekolahku-api.govtechmy.xyz

GET {{url}}/siaran
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw

### Search siaran
GET {{url}}/siaran?search=Penangguhan
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw

### Get Siaran By ID
GET {{url}}/siaran/{{SiaranID}}
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw

### Get Siaran Categories
GET http://localhost:3000/siaran/categories
Content-Type: application/json
Sekolahku-X-Api-Key: ABC343423232o3u243udbsjdfbw