/* eslint-disable no-unused-vars */
export const ROLES = ['admin', 'editor', 'viewer'] as const

export type Role = (typeof ROLES)[number]

export enum RESPONSE_STATUS {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}

export enum SEKOLAH_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum NEGERI {
  JOHOR = 'JOHOR',
  KEDAH = 'KEDAH',
  KELANTAN = 'KELANTAN',
  MELAKA = 'MELAKA',
  NEGERI_SEMBILAN = 'NEGERI_SEMBILAN',
  PAHANG = 'PAHANG',
  PERAK = 'PERAK',
  PERLIS = 'PERLIS',
  PULAU_PINANG = 'PULAU_PINANG',
  SABAH = 'SABAH',
  SARAWAK = 'SARAWAK',
  SELANGOR = 'SELANGOR',
  TERENGGANU = 'TERENGGANU',
  WILAYAH_PERSEKUTUAN_KUALA_LUMPUR = 'WILAYAH_PERSEKUTUAN_KUALA_LUMPUR',
  WILAYAH_PERSEKUTUAN_LABUAN = 'WILAYAH_PERSEKUTUAN_LABUAN',
  WILAYAH_PERSEKUTUAN_PUTRAJAYA = 'WILAYAH_PERSEKUTUAN_PUTRAJAYA',
  WEST_MALAYSIA = 'WEST_MALAYSIA',
  EAST_MALAYSIA = 'EAST_MALAYSIA',
}

export enum PERINGKAT {
  RENDAH = 'RENDAH',
  MENENGAH = 'MENENGAH',
}

export enum MARKER_GROUP {
  GROUP = 'GROUP',
  INDIVIDUAL = 'INDIVIDUAL',
  NEGERI = 'NEGERI',
  PARLIMEN = 'PARLIMEN',
  WEST_EAST_MALAYSIA = 'WEST_EAST_MALAYSIA',
  WEST_MALAYSIA = 'WEST_MALAYSIA',
  EAST_MALAYSIA = 'EAST_MALAYSIA',
  MALAYSIA = 'MALAYSIA',
}
